### ISSUE TITLE
can't run on mac

### ISSUE THREAD

**Issue by jerryyip** [Neutree/COMTool#1]
I got the following error on my macos 10.13, but i could run a pyqt5 program on mac before. Do you know how to fix this?
```
Traceback (most recent call last):
  File "/usr/local/bin/comtool", line 7, in <module>
    from COMTool.Main import main
  File "/usr/local/lib/python3.6/site-packages/COMTool/Main.py", line 3, in <module>
    from COMTool.Combobox import ComboBox
  File "/usr/local/lib/python3.6/site-packages/COMTool/Combobox.py", line 1, in <module>
    from PyQt5.QtWidgets import QComboBox,QListView
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/PyQt5/QtWidgets.so, 2): Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /usr/local/lib/python3.6/site-packages/PyQt5/QtWidgets.so
  Reason: image not found
```

**Comment by jerryyip** [comment]
It is fine now. I am able to run it in an virtualenv. Feel free to close the issue. It works well for me, except a little bug:
<img width="152" alt="bug" src="https://user-images.githubusercontent.com/18615354/35430339-d0fcffb6-02b2-11e8-830c-140184496a73.png">
The combobox shows all the usb devices, but all we need is the serial devices with a name "/dev/cu.usb*".
Anyway, thank you very much!

**Comment by Neutree** [comment]
I havent test on mac just for I have no mac machine, you are welcome to use this software

**Comment by jerryyip** [comment]
Hi my old iron, I have package this application with pyinstaller. Here is the link:
[COMTool.app.zip](https://github.com/Neutree/COMTool/files/1669819/COMTool.app.zip)
Anyone with mac os 10.13 is able to use this app without installing the environment(py3, pyqt5, etc.)

**Comment by donny681** [comment]
你有信仰吗 哈哈哈
