### ISSUE TITLE
打开串口长时间运行后， 运行卡顿

### ISSUE THREAD

**Issue by sunzigang** [Neutree/COMTool#103]
打开串口， 进行长时间的数据收发后会有明显的卡顿现象。 命令行有报错， cpu利用率提升到20%左右
命令行运行时报错：
![image](https://github.com/Neutree/COMTool/assets/35128999/9d4f9d82-ed9f-4330-8ba5-d2d17e98918e)

cpu占用率：
![image](https://github.com/Neutree/COMTool/assets/35128999/83f1a81f-295f-4216-8537-aaa2e2b3b416)

**Comment by Neutree** [comment]
估计是数据太多界面卡顿，然后处理不过来了？我猜，另外我看了下代码接收那里的lock写法有问题的，有空我测试修一修。也欢迎你修改提交PR哦

**Comment by sunzigang** [comment]
> 估计是数据太多修改界面卡顿，然后处理了？我猜，另外我查看了下代码接收那里的锁写法有问题的，有空我测试修改一修改。也欢迎你提交PR哦

不是数据太多导致的卡顿， 是死锁了
![image](https://github.com/Neutree/COMTool/assets/35128999/17ff7128-72d9-4f96-9436-0308d86a80b7)

**Comment by sunzigang** [comment]
对unix的颜色我不太清楚， 不明白len(text) - 10 + idx + 2 具体含义 所以无法提交pr  或者可否解释下这句话什么意思？

**Comment by Andy-Home** [comment]
我页遇到了该问题，有处理办法么

**Comment by Neutree** [comment]
更新了代码，应该解决了，有问题再打开issue
