### ISSUE TITLE
请求支持ARM版本的MAC

### ISSUE THREAD

**Issue by lihk11** [Neutree/COMTool#105]
如题，请求支持M1 M2系列的mac

**Comment by Neutree** [comment]
哦对哦 有空弄弄

**Comment by Neutree** [comment]
看了一下，貌似GitHub action 还没看到 arm版本的机器   https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

**Comment by wh201906** [comment]
按理说苹果的ARM机器可以直接运行x86程序的啊，Rosetta会翻译指令的

**Comment by huhu6608** [comment]
m1 可以运行的

**Comment by huhu6608** [comment]
最大的问题是。。。调不了字体大小，费眼
![WX20230813-003310@2x](https://github.com/Neutree/COMTool/assets/33958010/4587a5a6-d71d-4d0c-b998-0967178cf4a1)

/

**Comment by wh201906** [comment]
> 最大的问题是。。。调不了字体大小，费眼 ![WX20230813-003310@2x](https://user-images.githubusercontent.com/33958010/260243458-4587a5a6-d71d-4d0c-b998-0967178cf4a1.png)
> 
> /

这个问题和mac吧
请参考#51

**Comment by Neutree** [comment]
> 最大的问题是。。。调不了字体大小，费眼 ![WX20230813-003310@2x](https://user-images.githubusercontent.com/33958010/260243458-4587a5a6-d71d-4d0c-b998-0967178cf4a1.png)
> 
> /

这个应该是高分屏没适配的问题，我手里没有这样的设备，所以没法优化

**Comment by huhu6608** [comment]
放弃了，qss里找了半天,太多了。。没找到

**Comment by wh201906** [comment]
如果只是改字体的话可以试一下QApplication的setFont()方法？
https://github.com/wh201906/SerialTest/blob/5f304cfc3df8e74551dc26a15eff1b27392f984f/src/settingstab.cpp#L151-L161

高分屏适配可以试一下QApplication的setAttribite(Qt::AA_EnableHighDpiScaling)
https://github.com/wh201906/SerialTest/blob/5f304cfc3df8e74551dc26a15eff1b27392f984f/src/main.cpp#L26

以上是C++的代码，不过pyqt应该也有对应的代码

**Comment by vae1970** [comment]
希望还是能出个arm的原生版本，现在只能用转译的
