### ISSUE TITLE
RK3588开发板无法正常使用该软件，请求优化

### ISSUE THREAD

**Issue by zhoaji** [Neutree/COMTool#107]
出现一下的错误：from PyQt5.QtWidgets import QWidget, QLabel, QVBoxLayout
ImportError: /usr/lib/python3/dist-packages/PyQt5/QtGui.cpython-38-aarch64-linux-gnu.so: undefined symbol: _ZTI18QOpenGLTimeMonitor, version Qt_5
安装的版本为树莓派版本PI

**Comment by Neutree** [comment]
可能QT5版本问题？推荐装 5.15.6 版本

**Comment by wh201906** [comment]
网上搜到了类似的问题和解决方法
https://dev.t-firefly.com/thread-125298-1-1.html

**Comment by Neutree** [comment]
我试了在rk3588+armbian 下是可以用的，手动装一下 python3-pyqt5: `sudo apt install python3-pyqt5`
然后装一下依赖，把 `requirements.txt`中的`pyqt5`一行删掉，然后`pip install -r requirements.txt`，最后`python COMTool/Main.py`即可运行
![image](https://github.com/Neutree/COMTool/assets/8625829/01667469-cee5-4e1e-8651-254ca0184482)
