### ISSUE TITLE
这里是不是多了一个分号 还是我python版本不兼容这种写法

### ISSUE THREAD

**Issue by yangCHEN121520** [Neutree/COMTool#117]
from PyQt5.QtCore import pyqtSignal, Qt, QRect, QMargins ,,QCoreApplication

删除该分号后我的程序正常运行

**Comment by Neutree** [comment]
是的，这是 #116 引入的BUG， 我修复一下

**Comment by Neutree** [comment]
https://github.com/Neutree/COMTool/commit/c637e199f91a01b7cb4be39b025263d92b315e74 已修复

**Comment by ZenithJet** [comment]
I am so sorry for inconvenience. https://github.com/Neutree/COMTool/pull/116 It is my first time to pull requests on github,hoping not causing too much trouble.....
