### ISSUE TITLE
如何清除发送记录？

### ISSUE THREAD

**Issue by yisuixinq** [Neutree/COMTool#12]

**Comment by Neutree** [comment]
软件里面没有写清除按钮什么的，
如果是用pip安装的软件，可以清空你的用户home目录下的`comtool.settings.config`文件来达到这个目的；
如果是Windows下载的打包的版本，清除目录下的这个文件的内容就好了。

**Comment by Neutree** [comment]
[v1.7.8](https://github.com/Neutree/COMTool/releases/tag/v1.7.8) 添加了清除按钮
