### ISSUE TITLE
在macOS下加载参数失败导致无法启动

### ISSUE THREAD

**Issue by Hakureirm** [Neutree/COMTool#123]
机器：**Apple MacBook Pro 13 M1，macOS 14.2.1**
comtool版本：**v3.4.1**，下载dmg安装app
启动就显示这些
<img width="532" alt="image" src="https://github.com/Neutree/COMTool/assets/60978629/d0ea1556-190a-4a75-8e49-8730a58e49cf">

**Comment by Neutree** [comment]
这是触发了一个 小bug，不过可以暂时使用清除 config 文件的方式修复，config 文件在 ~/.config/comtool

**Comment by Neutree** [comment]
已修复 下次发布新版本就好了。现在你暂时先用删除 配置文件的方式修复吧，应该是你用了旧版的把自动换行时间设置为小于等于0的值触发了这个bug

**Comment by Hakureirm** [comment]
好，清除config后暂时能用了，非常感谢！
