### ISSUE TITLE
希望增加更精细的时间戳

### ISSUE THREAD

**Issue by SamulePope** [Neutree/COMTool#131]
使用串口接收数据，在已经勾选时间戳的情况下，也只有最开始有一个时间戳标记，后面的数据都是连续着的没有时间戳，希望能够改进一下，保存文件的时候也可以选择是否加上时间戳，是否换行。在”协议“一栏右侧的接收框倒是可以看到明显的换行分段，但是无法时间戳选项。
感谢！

**Comment by Neutree** [comment]
![image](https://github.com/Neutree/COMTool/assets/8625829/3d44887e-8d80-4eee-8003-78a57fcde3e7)

这个时间值设置小一点试试

**Comment by SamulePope** [comment]
确实有用，感谢！！！
