### ISSUE TITLE
启动慢，是否考虑先弹出logo告知用户正在打开，避免重复点击？

### ISSUE THREAD

**Issue by Lj-dog** [Neutree/COMTool#144]
点击打开后要过两分钟才显示logo，非常容易误以为没点击成功进而重复打开的。
我看run.log里发现从loading config complete 到 init main window需要花费 2分钟，这阶段是做什么操作是否能优化呢？
<img width="342" alt="2" src="https://github.com/user-attachments/assets/69edc79d-9652-40c7-99f3-e712bd1d53ec">
我看内存占用也不算高。
<img width="524" alt="1" src="https://github.com/user-attachments/assets/d7bdbb4b-99d3-4ab5-b908-ba9197496332">

**Comment by Neutree** [comment]
一般是第一次打开比较慢，打开了一次有缓存就好了，而且不是有logo显示麻，代码中关键词是 splash

**Comment by Lj-dog** [comment]
> 一般是第一次打开比较慢，打开了一次有缓存就好了，而且不是有logo显示麻，代码中关键词是 splash

<img width="341" alt="3" src="https://github.com/user-attachments/assets/1dfee29f-9246-4b90-a3ea-2b2de5e621f7">  

并没找到此关键词。  

有时确实会启动很快，但并不是第一次缓慢后面就好了。非专业python不太清楚机制是什么。

**Comment by Lj-dog** [comment]
![Uploading 4.png…]()

**Comment by Lj-dog** [comment]
<img width="357" alt="4" src="https://github.com/user-attachments/assets/3eebd5ec-1401-45d7-a535-35aade521541">

**Comment by Neutree** [comment]
![image](https://github.com/user-attachments/assets/b60315d6-3aec-4898-a432-8ca511e36c73)

**Comment by Neutree** [comment]
就是在加载Python 以及 QT的一些库什么的需要时间

**Comment by Lj-dog** [comment]
哦 这是PYQt啊，有意思。第一次见在pycharm上写

**Comment by Bendikos** [comment]
我也遇到了这个问题，关闭杀毒软件（包括但不限于Windows防火墙）即可
