### ISSUE TITLE
希望添加，对自定义串口命令，以一定时间间隔，一键发送的功能。

### ISSUE THREAD

**Issue by rzy0901** [Neutree/COMTool#147]
![image](https://github.com/user-attachments/assets/e7265a9b-b41f-4998-8c90-22bf732bb5e8)

**Comment by Neutree** [comment]
左边够上定时发送，点击一个就会自动发你点过的那个了

**Comment by rzy0901** [comment]
> 左边够上定时发送，点击一个就会自动发你点过的那个了

感谢回复，但是这个定时发送似乎只能够实现单个指令的延迟发送。有没有可能，一键将多个指令以固定时延发送呢？

**Comment by Neutree** [comment]
实现是可以实现的，不过需求得理清，点一下发送，所有项目都依次发送，发送多少次，这些乱七八糟的功能要说的话可以做，只是我肯定懒得做了，有兴趣的可以讨论 提交PR

**Comment by rzy0901** [comment]
> 实现是可以实现的，不过需求得理清，点一下发送，所有项目都依次发送，发送多少次，这些乱七八糟的功能要说的话可以做，只是我肯定懒得做了，有兴趣的可以讨论 提交PR

哦哦，我可以在闲暇时间研究一下这些需求，如果可以搞出来，到时候可以提交PR。
