### ISSUE TITLE
Support: How to generate PyInstaller executable that works with ARM CPU macOS

### ISSUE THREAD

**Issue by wilmer-suarez-simplisafe** [Neutree/COMTool#156]
Hello,

I tried generating a PyInstaller executable on macOS 14.6.1 (Apple M2) but when I double-click it, it fails to open. 
Downloading the `comtool_macos_11` `dmg` from the releases page works fine. How do I generate an executable like that?

**Comment by Neutree** [comment]
https://github.com/Neutree/COMTool/blob/master/.github/workflows/release_macos.yml
