### ISSUE TITLE
Mac 安装成功怎么打开COMTool?

### ISSUE THREAD

**Issue by lhzlg3368** [Neutree/COMTool#16]
Mac 已经安装了COMTool 1.7.8成功了。奈何我不知道怎么打开，怎么使用？

**Comment by Neutree** [comment]
终端输入comtool

**Comment by lhzlg3368** [comment]
@Neutree 我的Mac Python环境有点乱。Python有Anaconda和Brew安装的，所以路径有点不一样。不过今天通过修改源码弄好了。多谢

**Comment by kicer** [comment]
同样打不开～～～ 最后找到安装目录后，点击可以正常打开。

**Comment by Neutree** [comment]
[v1.7.8](https://github.com/Neutree/COMTool/releases/tag/v1.7.8) 使用dmg文件安装
