### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by matrixant** [Neutree/COMTool#19]
建议增加串口内容保存功能
建议增加串口数据添加时间戳功能

**Comment by Neutree** [comment]
功能已经添加， 包括保存到文件，以及添加时间戳， 还有更多支持，比如支持显示unix颜色，记录发送内容等

代码已经推上来了，打包等后面正式版更新就好了

![image](https://user-images.githubusercontent.com/8625829/145019740-d21ea35e-bb17-4c45-978f-5837216e2edd.png)
