### ISSUE TITLE
可以通过命令去发送信息吗

### ISSUE THREAD

**Issue by rabbitooops** [Neutree/COMTool#20]
因为我用的是nodejs，所以希望通过命令后去调用这个软件去发送接受消息？请问作者这个功能支持不？

**Comment by Neutree** [comment]
你的意思是nodejs操作串口么， nodejs有操作串口的库吧，比如serialport

这个软件是GUI界面，没有做API给其它软件调用，也没有命令行命令接口

**Comment by rabbitooops** [comment]
好的 谢谢
