### ISSUE TITLE
Mac: OPEN 之后无法 CLOSE，只能拔掉usb线

### ISSUE THREAD

**Issue by bingcheng1998** [Neutree/COMTool#22]
## 1. Mac: OPEN 之后无法 CLOSE，只能拔掉usb线 [BUG]
![](http://ww1.sinaimg.cn/large/006tNc79ly1g36do2atv2j30zz0u0q6m.jpg)

## 2. [功能建议] 现在无法自动跳转最底部

建议增加跳转底部功能。

**Comment by amoviolin** [comment]
刚入手python，装了环境，能运行，但是没弄明白这个图形界面是怎么和代码联系起来的。
我用designer没发现可以联系起来。是不是我把环境没弄对》？

**Comment by Neutree** [comment]
@bingcheng1998 把右边的条条拉到最底下，就会自动滚动到底部，如果不是底部它就不会自动滚动，这是为了方便查看，如果一直滚动到底部，数据量大了就完全看不清在发什么了；

至于打开了无法关闭的我木有遇到，而且我木有mac哈哈哈哈，有mac的大佬

**Comment by Neutree** [comment]
@amoviolin 这个界面是我用pyqt5手撸的，没有用UI设计器，如果用UI设计器的话会是一个`.ui`的单独文件

因为这个软件功能比较简单，而且我个人比较喜欢手撸，所以你用UI设计器不一定能看到效果

至于运行的话，直接用 python3 执行 main.py 就好了，中间提示却啥库你就用`sudo pip3 install ...`就好了

**Comment by amoviolin** [comment]
明白了。谢谢大神指点。。。

**Comment by chen707070yi** [comment]
谢大神的分享，一直在找类似的软件，谢谢大神开源了，我打算在您代码的基础上改进，加入modbus调试功能，先好好学习您的代码，谢了。

**Comment by Neutree** [comment]
年代久远，这个问题先关掉啦~ 有新问题重新开 issue 哦
