### ISSUE TITLE
配置文件能不能换个隐藏文件

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [Neutree/COMTool#24]
配置文件能不能弄到~/.comtool里面，这样眼不见为净，linux下，也没有办法和windows下一样设置隐藏文件，看的郁闷

**Comment by Neutree** [comment]
Linux下按Ctrl+H就能隐藏了，
或者可以改源码中的文件储存路径

**Comment by Neutree** [comment]
额对哦，配置文件不是隐藏文件。。。那我找时间改一下

**Comment by Neutree** [comment]
已经换成隐藏文件夹了，[v1.7.8](https://github.com/Neutree/COMTool/releases/tag/v1.7.8)，明天打包一个
