### ISSUE TITLE
fail to execute script Main

### ISSUE THREAD

**Issue by wangyuanzhengbighead** [Neutree/COMTool#25]
i try to 
“pip3 install pyinstaller
python pack.py
cd dist” to install on win10,then i open "/dist/comtool/comtool.exe", it runs a error 

![image](https://user-images.githubusercontent.com/38694798/63825082-e5875700-c98b-11e9-9f4e-1e1da7b60c97.png)

**Comment by Neutree** [comment]
Just download from release here if you don't change any code: [release](https://github.com/Neutree/COMTool/releases)

Or you must install requirements firstly:
```
pip3 install -r requirements.txt
```
and ensure you can run Main.py by:
```
python3 Main.py
```

then pack with pyinstaller:
```
pip3 install pyinstaller
python pack.py
```
