### ISSUE TITLE
可否记忆上次使用的皮肤？

### ISSUE THREAD

**Issue by frondescexxx** [Neutree/COMTool#27]
win10下，每次打开先是浅色再切换为深色。有时需要一直用浅色皮肤，可否加入记忆功能而不是每次打开都重置为深色，感谢开发者。

**Comment by Neutree** [comment]
这个功能是有的哦~你是不是哪里看错了或者使用错误呢

**Comment by Neutree** [comment]
我先关闭这个问题咯，还有问题再打开
