### ISSUE TITLE
几个功能建议

### ISSUE THREAD

**Issue by tumuyan** [Neutree/COMTool#29]
不知道还会继续开发嘛？提几个功能建议
1.  UI上同时显示tx.rx的内容，用不同颜色来区分
2.  可以判断监控串口连接是否已经断开，如果设备断开就回显一行comx已经离线，如果设备重连自动重新打开串口提示comx重新上线
3. 已经发送的命令可以以侧边栏列表显示，目前点击下拉框的操作效率有点低

**Comment by Neutree** [comment]
2 以后会优化, 1和3 不会做

**Comment by Neutree** [comment]
1和2已经做好
1： 发送和接收会在前面添加`=>`或者`<=`
2： 串口断开会显示连接丢失
![image](https://user-images.githubusercontent.com/8625829/145019395-9863327d-d2c3-4a9b-af62-5f8dd11a7089.png)


功能三近几天也会添加，不过不是历史，而是自定义内容

**Comment by Neutree** [comment]
自定义发送也加好了，可以在右边这里保存一些常用的，数量不限， 这些功能源码都推送了

![image](https://user-images.githubusercontent.com/8625829/145144994-3d83dad1-dc6f-4031-b8f7-c28f9ebc0e8b.png)
