### ISSUE TITLE
cxsetup don't work

### ISSUE THREAD

**Issue by MoonOfAnt** [Neutree/COMTool#3]
I run the cxsetup.py and input "setup()" but there is nothing happened.
I want to make it a ".exe" but it can't succeed when i use the "pyinstaller" straight.
Could you help me please?
Thank you.

**Comment by MoonOfAnt** [comment]
In cmd, When i input " python3 cxsetup.py build", it couldn't build a ".exe" successfully.

**Comment by Neutree** [comment]
use pyinstaller instead
```
pip3 install pyinstaller
python3 pack.py
```
