### ISSUE TITLE
comtoolMac版本不支持多实例？

### ISSUE THREAD

**Issue by karlzheng** [Neutree/COMTool#30]
comtoolMac版本不支持多实例？

**Comment by Neutree** [comment]
不支持,可能是打包工具的特性, 用的 https://github.com/sindresorhus/create-dmg , 可能另外一个 create-dmg 程序(brew安装的) 可以吧, 有兴趣可以试试

如果临时用可以打开终端, 
```
cd /Applicatioin/comtool.app/MacOS
./comtool
```

这样的方式可以打开多个

**Comment by Neutree** [comment]
![image](https://user-images.githubusercontent.com/8625829/147112700-b0782d4d-3d04-44bb-90d4-888d12efd998.jpeg)

添加了多窗口支持，需要注意的是配置文件仍然使用的同一份配置文件
