### ISSUE TITLE
可以进行二次开发吗

### ISSUE THREAD

**Issue by tianyinggang** [Neutree/COMTool#31]
希望有完整的API文档，方便二次开发

**Comment by Neutree** [comment]
emmm 这是一个应用,暂时没有API, 其实代码量不大, 看一下就懂了

**Comment by Luxni** [comment]
emmmmmm

希望能把界面给分离出来，个人认为后面用qt designer设计UI方便一点。

**Comment by Neutree** [comment]
xml no!!!

css yes!!!

**Comment by Neutree** [comment]
@Luxni  不用 UI 文件的原因是不太好控制布局，拖动出来的UI文件非常喜欢使用绝对布局， 最近尝试把界面简单给分离了一下， 界面都以插件的形式加载了: https://github.com/Neutree/COMTool/blob/master/COMTool/plugins/base.py

界面都在这几个函数返回一个 QWidget 就好了， 所以不管是 UI 文件还是代码都可以
```python
    def onWidgetMain(self):
    def onWidgetSettings(self,):
    def onWidgetFunctional(self):
```

**Comment by Neutree** [comment]
插件功能已经开发好了，参照 docs 文件夹中的插件开发即可开发即可，这个issue先关闭了，有问题的建议再新开
