### ISSUE TITLE
mac 安装 brew 报错了

### ISSUE THREAD

**Issue by imouyanghuan** [Neutree/COMTool#4]
log 如下：

OYHmac:~ ouyanghuan$ brew install python3 python3-pip

Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz
######################################################################## 100.0%
==> Pouring portable-ruby-2.3.3_2.leopard_64.bottle.tar.gz
==> Homebrew has enabled anonymous aggregate user behaviour analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Failure while executing: git config --local --replace-all homebrew.analyticsmessage true
Error: No available formula with the name "python3-pip"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.

**Comment by Neutree** [comment]
这个网上应该有很多回答，可以搜一搜，比如
```
xcode-select –install
```

我先关闭这个issue了～～
