### ISSUE TITLE
Comtool.exe Library

### ISSUE THREAD

**Issue by MartinSokolov15** [Neutree/COMTool#41]
Hi, when i try to run comtool.exe i've got this error
![COMtool](https://user-images.githubusercontent.com/64197840/134665783-9a5dd641-f79d-4818-9b9b-e17a2afd1215.jpg)

Any help ?

**Comment by Neutree** [comment]
it's build by your self? make sure you can run with `python ComTool/Main.py` first

**Comment by MartinSokolov15** [comment]
I try, but it's the same result when i then run comtool.exe

**Comment by Neutree** [comment]
you can not execute the build dir's exe file, you should use the dist directory's

![Uploading image.png…]()

**Comment by MartinSokolov15** [comment]
I try and i've got this
![COMtool_Error](https://user-images.githubusercontent.com/64197840/135750476-776c338c-93af-436b-8d3f-3527b42a83b4.jpg)

**Comment by MartinSokolov15** [comment]
ERROR: Cannot install requests==2.22.0 and urllib3==1.26.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested urllib3==1.26.5
    requests 2.22.0 depends on urllib3!=1.25.0, !=1.25.1, <1.26 and >=1.21.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by Neutree** [comment]
。。。。 `pip install -U urllib3` and `pip install -U requests`  I don't what you want to, maybe you should learn more about Python basic knowledge

**Comment by MartinSokolov15** [comment]
I'm a beginner

**Comment by MartinSokolov15** [comment]
How to fix this ?

File "C:/COMTool-master/COMTool/Main.py", line 7, in <module>
    from COMTool.Combobox import ComboBox
  File "C:\COMTool-master\COMTool\Combobox.py", line 1, in <module>
    from PyQt5.QtWidgets import QComboBox,QListView
ImportError: DLL load failed while importing QtWidgets: The specified module could not be found.

**Comment by Neutree** [comment]
PyQt5 installation has some error maybe
