### ISSUE TITLE
CRLF not work.

### ISSUE THREAD

**Issue by e71828** [Neutree/COMTool#42]
![屏幕截图 2021-12-02 201653](https://user-images.githubusercontent.com/24602820/144420528-6c85a088-4057-45a9-8378-8e654b225b2c.png)
 
版本 1.7.9

**Comment by Neutree** [comment]
?
你都没有发送回车

**Comment by e71828** [comment]
CRLF 不是自动坠上的吗

**Comment by e71828** [comment]
![image](https://user-images.githubusercontent.com/24602820/144545415-085b1ec9-32fb-47cf-8407-69e33cb5336a.png)

手动加 '\r\n' 系统不认

**Comment by e71828** [comment]
> ? 你都没有发送回车

建议提示一下 发送新行 是需要 回车 的，且在 ASCII下

**Comment by Neutree** [comment]
是的 默认不会发送回车的  但是这个试下就知道了

以后有空大版本更新的时候可以给CRLF加个提示说明

**Comment by e71828** [comment]
> ![image](https://user-images.githubusercontent.com/24602820/144545415-085b1ec9-32fb-47cf-8407-69e33cb5336a.png)
> 
> 手动加 '\r\n' 系统不认

- [ ] escape character support, like \x \r \n etc.

这个feature 看来还不支持

**Comment by xhc-code** [comment]
我以为这个是自动追加回车，没想到是保留文本内的回车信息。我有个疑问，这个框的作用是什么？历史记录？
![image](https://github.com/Neutree/COMTool/assets/28866025/498feeb4-7fdf-4ffb-9556-1527490de360)

**Comment by Neutree** [comment]
@xhc-code  CRLF 是设置发送的回车符号是`\n`还是`\r\n`，具体什么时候发是其它地方控制的，比如这些地方：
![image](https://github.com/Neutree/COMTool/assets/8625829/79c6fe9f-c4de-480e-91d7-d243729a0eab)


可以多试试就懂了

下拉框是历史记录

**Comment by xhc-code** [comment]
> @xhc-code CRLF 是设置发送的回车符号是`\n`还是`\r\n`，具体什么时候发是其它地方控制的，比如这些地方： ![image](https://user-images.githubusercontent.com/8625829/278930336-79c6fe9f-c4de-480e-91d7-d243729a0eab.png)
> 
> 可以多试试就懂了
> 
> 下拉框是历史记录

我发送的原记录就是 我是贵！，频繁手动通过js串口进行发送，我看了发送的字符串都是全的，但是软件接收的信息不全（需要频繁多次点击，涉及偶发）。
![image](https://github.com/Neutree/COMTool/assets/28866025/7449ad17-9730-45fe-a1c0-28f7771ad590)
