### ISSUE TITLE
win版本，编译好的，没有功能列表

### ISSUE THREAD

**Issue by erwzqsdsdsf** [Neutree/COMTool#43]
提示等待中。截图区域有呀

**Comment by Neutree** [comment]
v1.7.9 是这样的
![image](https://user-images.githubusercontent.com/8625829/145346344-c41657bc-c9f8-4248-86f0-8443546a70fb.png)

v2.0以后的是这样的, 但是 2.0我还在打包测试， 需要等待下下，如果你着急可以直接拉取源码用`pip install .`来安装

![image](https://user-images.githubusercontent.com/8625829/145346417-83eb1dc5-a064-4c4a-8e01-a78ac8271a32.png)

**Comment by Neutree** [comment]
这里下载最新的就有了  https://github.com/Neutree/COMTool/releases
