### ISSUE TITLE
请问如何显示二维码

### ISSUE THREAD

**Issue by wh201906** [Neutree/COMTool#48]
需要发送什么才能在COMTool上显示二维码呢？

**Comment by Neutree** [comment]
截图那个二维码是 esp32 的固件打印的二维码，用的特殊符号打的, 代码应该是这个 https://github.com/Neutree/struggler_care/blob/88be7665568559f73b59e30faa522b6ca4e60423/remote_power_ctrl/src/provisioning/qrcode/src/qrcode.c

就类似这样的特殊符号

█▀▀▀▀▀█ ▄ ▄ █▄█▄█▀█ ▀█ ▀▄ █▄█ █▀▀▀▀▀█   
  █ ███ █ ▄▄▄▄▀▄ ▀█▄  █▀█ ▀▄▄ ▀ █ ███ █   
  █ ▀▀▀ █ ▄█  ▄ ▀▄  ▀▀█▀▄▀  ▄▄█ █ ▀▀▀ █   
  ▀▀▀▀▀▀▀ ▀▄█ █ █ ▀ █▄▀▄█▄▀ █▄▀ ▀▀▀▀▀▀▀   
  ████▀ ▀█▀█▄▀ ▀ ▀██▀▄▄▄▀█▄█ ▄█ █ █▄█    
   ▀█  █▀▄▀ █ █▀▀██   ███    ▀█▀█▄██▀▄▀   
  ▀▄██ ▀▀▀▄▀▄▀ █▀▀▄▄▄▄█ ▄▄▀▀█  ▀▀ ▀▀█▄▀   
  ▄▄█ █▀▀██  ▄ ▀▀▀▄ ▀ ▄██▄▄  ████▄ ▄▀▀█   
  ▄  ▄▀▀▀▄▄▀▀▀ ▀▀▀█▄▄▄▄▄█▄▀█▀ ▄▀▀▄▀▀█▄▀   
  ▄██▀▄█▀▄█   ▀ ▄▀▄▀▄▄█▄▄ ▄ ▀█▀ █  ▀▀█   
   █▄██▄▀ ██▄▄▀█▀▀  ▄█▄ ▀█▀█▀ ▄▀▀█▀███▀   
  █ ▀▄▀▀▀▄ ▀▀   ██▀  ▄ ▄█▄▀▀█▀▀▄▀██  ▀█   
  █▀ ▄▄ ▀▀▄▀▀▄ ▀▀ ▀▄▄▄█▄▀▄ ▀█▀▄▀▀▄▀▀██▀   
  █ █ ▀█▀▄▄▀▄▄  ███▀▀  ▄▀  ▀ ▀▄██▄▄ ▀▀█   
  ▀ ▀ ▀ ▀▀▄█ █▀█▄▄▄  ▄█▄█▄▀▀▀█▀▀▀█ ▀     
  █▀▀▀▀▀█ ▀   ▀ ██▄▀▄▄▄█▀ ▀ █▄█ ▀ ██ ▀█   
  █ ███ █ █▀ █▀▀█▀▀  ▄ ▄▀▄▀▀██▀██▀█▀█     
  █ ▀▀▀ █ ██▀▄▄ ▀█▀ ▄  █▄▄ ▀  ▄▄ █▄▀▀▀█   
  ▀▀▀▀▀▀▀ ▀▀▀ ▀▀▀ ▀   ▀ ▀▀▀▀       ▀▀▀▀

**Comment by wh201906** [comment]
感谢！
