### ISSUE TITLE
receiveData咨询

### ISSUE THREAD

**Issue by jackgreentemp** [Neutree/COMTool#5]
首先感谢分享
`receiveData` 函数中有一句 `time.sleep(0.009)`，想请教一下这句的作用是什么？还有就是`0.009`是怎么计算出来的呢？

**Comment by Neutree** [comment]
在C++中可能会设置串口中断回调函数，这样串口数据到达后就可以立马获得数据；

但是python中我使用了一个比较简单粗暴的方法，就是开了一个线程死循环读取串口，这样做的好处就是简单可靠，但是缺点就是因为是死循环，性能会有问题，CPU占用会过高，所以在这里延时了一下下释放一下CPU占用，至于为啥是0.009，是我看着CPU使用率以及不停地给串口发数据综合的情况下取的一个值2333333

如果你有什么更好的解决办法就更好了

**Comment by Neutree** [comment]
其实也许可以用read函数阻塞等待更好
http://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial.read

**Comment by Neutree** [comment]
是的，pyserial没有事件，都是死循环读取。

两种方式都可以的，看你具体的要求了，反正串口助手为了实时性死循环更好，你的程序没有响应可能引起的原因很多了，多半是你的UI显示的问题，这个得你自己多调试调试找问题了

**Comment by jackgreentemp** [comment]
嗯，非常感谢
特别诡异的是，接收数据线程不加`time.sleep`，程序就能多跑一会儿...

**Comment by Neutree** [comment]
加sleep界面会死掉多半就是你的sleep是在UI线程调用的了~~
