### ISSUE TITLE
已收录 Windows Scoop 桶

### ISSUE THREAD

**Issue by StudentWeis** [Neutree/COMTool#50]
首先非常感谢作者大大！

我把您的作品收录到了我的 Scoop 桶中，Windows 用户可以通过 Scoop 很轻松地安装最新版的 COMTool。如下方式：

```sh
scoop bucket add Nightly https://github.com/StudentWeis/Nightly
scoop install comtool
```

您可以在 README.md 中添加说明！

**Comment by Neutree** [comment]
非常棒！下次更新的时候加到readme中去

**Comment by Neutree** [comment]
加上了，作为一个可选项，非常不错 https://github.com/Neutree/COMTool#windows

**Comment by StudentWeis** [comment]
嗯！真好！
