### ISSUE TITLE
颜色

### ISSUE THREAD

**Issue by qhdHGP** [Neutree/COMTool#52]
![image](https://user-images.githubusercontent.com/70582901/163295680-f8e71ef7-dda2-47ee-a5c2-71fed8b5e1a9.png)
有时候不能够添加颜色

**Comment by Neutree** [comment]
应该是包被分割了，目前代码里面是从每个包检测颜色控制符，控制符被分割成两个包了，所以可以保证发送颜色控制符号的时间间隔不要太长来避免，有时间我优化下这个问题

**Comment by qhdHGP** [comment]
你好，这边发现一个其他的问题，有时候串口的数据接收会接收不完整，
![1650425809(1)](https://user-images.githubusercontent.com/70582901/164145699-9cbfef76-6d07-49fc-bdee-b62144b58952.jpg)
![1650425790](https://user-images.githubusercontent.com/70582901/164145712-2bed21a9-fbbb-4c5e-bee7-a71e4824b9e4.jpg)

**Comment by Neutree** [comment]
丢数据应该不太可能  这部分功能应该挺可靠的，能用什么方法复现吗

**Comment by qhdHGP** [comment]
对的，我弄错了，应该不是接收不到，而是没有显示出来，就是这个数据明明是一包一包发的，但是数据会连着下一包一起显示出来

**Comment by Neutree** [comment]
接收代码在这里， https://github.com/Neutree/COMTool/blob/f08b32eba3fb0595fd37e5aec3a8d9a556182730/COMTool/conn/conn_serial.py#L434-L447 ， 可能还有已优化缓冲区的处理

**Comment by Neutree** [comment]
尝试修复了 fe37bf8a02fed6a4ed4c609204d61a323e46d569 ， 可以拉取最新代码试试

**Comment by Neutree** [comment]
先关闭了，有问题再打开或者新建issue
