### ISSUE TITLE
定时发送修改存在闪退问题

### ISSUE THREAD

**Issue by cxxfff** [Neutree/COMTool#55]
定时发送的参数栏里，如果把数字全部删掉（准备重新输入数字），软件会自己关闭

**Comment by Neutree** [comment]
软件版本比较旧？ 下载最新的试试，不过最新的输入框为空时会弹提示，我可以改改

**Comment by Neutree** [comment]
https://github.com/Neutree/COMTool/commit/d5b8daef8fe2f583abc80064a42bc52276162d8d  改好了，现在输入框空了会变成默认的 300ms（接收200ms），不会弹框警告了，软件闪退可能是旧版的问题，现在不存在了

**Comment by tr4v3ler** [comment]
> [d5b8dae](https://github.com/Neutree/COMTool/commit/d5b8daef8fe2f583abc80064a42bc52276162d8d) 改好了，现在输入框空了会变成默认的 300ms（接收200ms），不会弹框警告了，软件闪退可能是旧版的问题，现在不存在了

请问收发窗口的定时发送功能所需发送的信息应该在哪里编辑？右下角的输入框里面编辑没有生效，是要打开侧边栏在自定义发送哪里编辑吗？

**Comment by Neutree** [comment]
@tr4v3ler  
![image](https://user-images.githubusercontent.com/8625829/219658227-099ce2ad-f724-43bf-8c4b-53ed30010d75.png)

勾上左边的定时发送，下面的正常发送框输入内容，然后点击发送就会自动发了

**Comment by tr4v3ler** [comment]
> @tr4v3ler ![image](https://user-images.githubusercontent.com/8625829/219658227-099ce2ad-f724-43bf-8c4b-53ed30010d75.png)
> 
> 勾上左边的定时发送，下面的正常发送框输入内容，然后点击发送就会自动发了

收到，多谢！
