### ISSUE TITLE
TCP接收数据有误

### ISSUE THREAD

**Issue by shineycoding** [Neutree/COMTool#58]
TCP接收数据，发现插件的onReceived()方法中接收到的数据，和插件的updateReceivedDataDisplay()方法中接收到的data数据不一致，被篡改了。也就是TCP客户端收到数据先通过onReceived()方法的接收，再是传递到插件的updateReceivedDataDisplay()方法。但是数据前后不一致。
问题：
1、onReceived()和updateReceivedDataDisplay()方法中间是在哪里改了数据？

**Comment by Neutree** [comment]
嗯？ 为什么close 了呢
