### ISSUE TITLE
串口打开False，实际打开成功，还有关闭串口也报错，用的pycharm+python3.5+pyqt5，win7 32位运行，持续关注中。。。。

### ISSUE THREAD

**Issue by Junkiwang** [Neutree/COMTool#6]
icon path:C:/Users/Administrator/Desktop/COMTool-master/COMToolData/assets/logo.png
data path:C:/Users/Administrator/Desktop/COMTool-master/COMToolData
1
Already latest version!
Serial<id=0x260edd0, open=False>(port='COM6', baudrate=9600, bytesize=8, parity='N', stopbits=1.0, timeout=None, xonxoff=False, rtscts=False, dsrdtr=False)

receiveData error
ClearCommError failed (OSError(9, '句柄无效。', None, 6))

**Comment by Junkiwang** [comment]
下载的文件中没看到已经打包好的版本呢

**Comment by Neutree** [comment]
。。。。

release页面：https://github.com/Neutree/COMTool/releases

![image](https://user-images.githubusercontent.com/8625829/41404300-6f968472-6ff9-11e8-9553-3e765c5cb00d.png)

**Comment by Junkiwang** [comment]
奥，可以打开串口，也能发数据，我的意思是调试发现的 Serial<id=0x260edd0, open=False>，是不是表示打开失败

**Comment by Neutree** [comment]
false确实是没有打开的意思，不过，你看代码里print(self.com)打印的地方是在串口还没打开的时候打印的，所以肯定始终为false的，至于你这个问题出在哪儿你可以调试一下就能找到问题啦
