### ISSUE TITLE
请问这个图表功能要这么用呢，收发数据没有绘图呀

### ISSUE THREAD

**Issue by Fancysy** [Neutree/COMTool#60]

**Comment by Neutree** [comment]
![image](https://user-images.githubusercontent.com/8625829/173232917-8de17ec5-0463-4e90-bfbb-5d071716e454.png)

![image](https://user-images.githubusercontent.com/8625829/173233144-59b5b93a-61c6-4153-9a3b-da8c76290f18.png)

按照这样拼接一个协议帧就好啦（顺便 这个帮助页面的例程写得比较简陋 能看懂就好哈哈哈哈）

**Comment by fbcgithub** [comment]
是一个发送一个接受，然后绘图吗，点击那个按钮发送数据吗，要怎样的格式呀

**Comment by Neutree** [comment]
不是。。。。 是其它设备或者程序给comtool发，comtool收到了后画图；

那个按钮是方便comtool给其它设备或者程序发送数据用的

**Comment by fbcgithub** [comment]
我在其他设备上用comtool给自己发，但是绘图没反应，要发怎样的数据呀

**Comment by Neutree** [comment]
> ![image](https://user-images.githubusercontent.com/8625829/173232917-8de17ec5-0463-4e90-bfbb-5d071716e454.png)
> 
> ![image](https://user-images.githubusercontent.com/8625829/173233144-59b5b93a-61c6-4153-9a3b-da8c76290f18.png)
> 
> 按照这样拼接一个协议帧就好啦（顺便 这个帮助页面的例程写得比较简陋 能看懂就好哈哈哈哈）

**Comment by fbcgithub** [comment]
Fancy 2 0.4 \xAA\xCC\xEE\xBB'这样的格式嘛，还是没有反应呀/(ㄒoㄒ)/~~

**Comment by Neutree** [comment]
emmm 你先用提供的python API调试下吧。。。肯定是可以的 你自己没发送对

**Comment by fbcgithub** [comment]
好的，万分感谢

**Comment by linghan1997** [comment]
请问调试成功了吗？我的graph也不显示曲线，不知道作者说的协议应该往哪里加

**Comment by Neutree** [comment]
@linghan1997  就是外部往comtool 发送数据呀， 每帧数据按照帮助里面的函数合成一帧数据， 发送给comtool 就好啦

**Comment by Neutree** [comment]
看帮助信息
![image](https://user-images.githubusercontent.com/8625829/233936909-8cc711a8-a7fa-446f-9fb9-d74cd9df4d4b.png)

总之就是按照协议合成一个包，然后通过串口或者 TCP 等方式发送到 comtool 就会显示了

**Comment by Shoulder404** [comment]
> 不是。。。。 是其它设备或者程序给comtool发，comtool收到了后画图；
> 
> 那个按钮是方便comtool给其它设备或者程序发送数据用的

comtool图表中的连接和数据发送端连接的设备需要如何配置

**Comment by Neutree** [comment]
> > 不是。。。。 是其它设备或者程序给comtool发，comtool收到了后画图；
> > 那个按钮是方便comtool给其它设备或者程序发送数据用的
> 
> comtool图表中的连接和数据发送端连接的设备需要如何配置

https://neucrack.com/p/186
