### ISSUE TITLE
可以给自定义发送按钮一个label位吗？

### ISSUE THREAD

**Issue by CotTan** [Neutree/COMTool#61]
给自定义按钮只显示label，命令值隐藏。即编辑状态和非编辑状态，命令行收窄之后也分不清是那条命令了

**Comment by Neutree** [comment]
这样吗  进入keymode不就好了

![image](https://user-images.githubusercontent.com/8625829/173503654-e7d3f398-96c5-45cc-86e1-51db4071db4c.png)
