### ISSUE TITLE
功能建议-自动发送附加位

### ISSUE THREAD

**Issue by clan4456** [Neutree/COMTool#63]
希望能增加发送数据时自动发送附加位的功能，可在发送数据时自动在数据末端增加常见的CRC/LRC/CheckSUM等常见校验字节。这样可方便调试。

举例：进行Modbus调试时，只需在输入框输入 01 03 00 0A 00 02 （03指令读000A~000B寄存器数据），点击发送后，自动发送实际的Modbus指令 01 03 00 0A 00 02 E4 09，（E4 09为自动根据Modbus CRC-16校验算法计算字节数据）

参考：
![](https://fastly.jsdelivr.net/gh/clan4456/Picture@main/clan/2022627111722_yjqir5n06c_1656299841405.png)

**Comment by Neutree** [comment]
有自定义协议功能， 可以实现此功能，并且更强大

**Comment by clan4456** [comment]
是在这个页面下使用吗？是通过改写decode和encode？decode是接收，encode是发送？但如果我要输入自定义的内容，也好像没有文本框可以输入发送内容啊？例如我要实现，发送时自动在发送内容后增加0x01 0x02两个字节数据，该如何实现？还望指点一下！
![](https://raw.githubusercontent.com/clan4456/Picture/main/clan/2022628095200_su664ip1mg_1656381119748.png)

**Comment by Neutree** [comment]
```
def encode(data):
    return data + b'\x01\x02'
```

发送内容修改右边的输入框就好了，比如`hello`，点击
![image](https://user-images.githubusercontent.com/8625829/176082166-5007d77f-6ede-48e0-b35c-e79761d82187.png)
按钮就能发送了

另外， 如果你是用`pip`安装的 comtool， 你也可以直接在代码里面 `import`外部模块，比如
先安装`crccheck`模块
```
pip install crccheck
```
然后修改代码
```
import crccheck.crc import Crc16Modbus

crc16_modbus = Crc16Modbus()

def encode(data):
    sum = crc16_modbus.calc(data)
    return data + sum.to_bytes(2, byteorder="little")

```

**Comment by clan4456** [comment]
明白了，非常感谢！
