### ISSUE TITLE
[建议] 能否加入 选择性显示功能（Filter text）

### ISSUE THREAD

**Issue by JamesJian-tech** [Neutree/COMTool#65]
平时使用terminal 信息很多 如果有一个过滤功能就很方便了 例如：

[time] hello hello
[time] hello
[time] hello
[time] hello
[time] hello
[time] world
[time] hello
[time] hello
[time] hello
[time] hello

其实只想知道 world 的出现点和时间 其他的hello 并不需要在terminal 里面出现 但可以存在.log 文件里面。

能否实现？

**Comment by Neutree** [comment]
可以在协议中实现， 自定义脚本 
```
def decode(data):
    if b"world" in data:
        return data
    return b''
```

**Comment by Neutree** [comment]
![image](https://user-images.githubusercontent.com/8625829/179165884-a2eee3f1-a343-4974-ba9a-81e15e31580f.png)

修改这里的代码， 代码格式是 python 格式， 有啥不懂的百度搜一下 python 怎么写

**Comment by JamesJian-tech** [comment]
这个是在protocol 里面。

Terminal 里面如果有搜索和过滤功能就更加完美。

**Comment by Neutree** [comment]
emmmmm terminal加过滤 没考虑做这个  你可以考虑做做2333
