### ISSUE TITLE
tcp 连接方式client增加可以自定义端口

### ISSUE THREAD

**Issue by vzhr** [Neutree/COMTool#66]
tcp连接时，有时候出口端口会有限制，希望可以增加自定义端口的选项

**Comment by Neutree** [comment]
? 

![image](https://user-images.githubusercontent.com/8625829/180756506-c359d2e2-9210-4537-b62d-756949034881.png)

那这个是什么

**Comment by vzhr** [comment]
当你选择作为client的时候没有可以选择端口选项

**Comment by vzhr** [comment]
> ?
> 
> ![image](https://user-images.githubusercontent.com/8625829/180756506-c359d2e2-9210-4537-b62d-756949034881.png)
> 
> 那这个是什么

当你选择作为client的时候没有可以选择端口选项

**Comment by Neutree** [comment]
![image](https://user-images.githubusercontent.com/8625829/183383073-14806e60-7bd0-4783-9625-c5b653123093.png)

那这是什么

**Comment by vzhr** [comment]
> 

这个是对方的端口，我的意思是可以指定自身（client）端口去连接对方。差点给我整不会了oro

**Comment by Neutree** [comment]
噢 我懂了，作为客户端的时候指定客户端自己的端口， 没办法， 你这提问方式有待改进啊，主谓宾语都不全。。。

一般不需要指定客户端自己的端口吧，都是自动生成的，我没有遇到过这样的错误诶
