### ISSUE TITLE
可以多开吗？

### ISSUE THREAD

**Issue by linmonsv** [Neutree/COMTool#67]
有时候需要同时侦听多个端口？现在软件只能开一份？

**Comment by Neutree** [comment]
现在可以开多个 tab， 同时多开软件也是支持的呀 你尝试过吗，不可以？

![image](https://user-images.githubusercontent.com/8625829/183383358-b64aa8f6-205f-4d39-b8ea-e25251dea1dc.png)

![image](https://user-images.githubusercontent.com/8625829/183383507-d85ffa98-c3f4-4efb-bf7f-65653283f7a5.png)
