### ISSUE TITLE
为何要将新版本打包成Pre-Release啊

### ISSUE THREAD

**Issue by kaidegit** [Neutree/COMTool#68]
是有什么不稳定因素，还是为了主推2.1啊，还是仅仅只是选错了

**Comment by wirano** [comment]
不发新的 release ，arch community 仓库的包版本号都不动了

**Comment by Neutree** [comment]
这样的嘛  因为改动比较大 怕有什么bug，不过过了挺久好像也没很大的bug，可以改成 release 了
