### ISSUE TITLE
There is a problem with Raspberry Pi 4B

### ISSUE THREAD

**Issue by Avalon1997** [Neutree/COMTool#74]
Hey！ There is a problem when I try to install your serial software COMtool on raspberry pi system , It seems doesn't work.

![image](https://user-images.githubusercontent.com/89969876/192444956-48774c9e-d694-4c6f-bfee-5aa1717f5a19.png)

it prompts that read timed out.
Why does such a problem occur ?

**Comment by Avalon1997** [comment]
I solved it........

**Comment by Neutree** [comment]
it seems network issue.
Normally, in Rasberry Pi, the biggest problem is install Pyqt5

**Comment by Avalon1997** [comment]
Yes, it is indeed caused by network fluctuations.
And before this i did have some problems installing PyQt.
Thanks  a lot!
