### ISSUE TITLE
Save log功能关不掉

### ISSUE THREAD

**Issue by hhhgyu** [Neutree/COMTool#78]
在填了log文件路径的情况下，总是会自动把数据写进文件里。
dbg.py里的onLog方法写错了
`if self.config["saveLogPath"]:`
应该改成
`if self.config["saveLog"] and self.config["saveLogPath"]!="" :`

**Comment by Neutree** [comment]
https://github.com/Neutree/COMTool/commit/4a2ddc97b916beaf8d0fe313ad069c77341d64ba 感谢 已经修复
