### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by XXXXzzzz000** [Neutree/COMTool#8]
有没有可能添加保存接收数据和字体颜色的支持呢?

**Comment by Neutree** [comment]
可以吧，不过得有空了再弄，最近比较忙，应该短时间内不会做

**Comment by Neutree** [comment]
两个功能已经添加

颜色使用方法，`\33[颜色m` 这里`颜色`可以设置前景和背景颜色，前景是`31~37`，背景是`41~47`，前景和背景都需要设置就用`;`隔开，比如`\33[31;43mhello\33[0m`  也可以十六进制 `\x1b[31;43mhello\x1b[0m`

![image](https://user-images.githubusercontent.com/8625829/145021194-d72096fb-edfb-4179-8212-c69abdc49058.png)

**Comment by XXXXzzzz000** [comment]
您的邮件我已收到。                                                             宣泽

**Comment by TurnOffNOD** [comment]
> 两个功能已经添加
> 
> 颜色使用方法，`\33[颜色m` 这里`颜色`可以设置前景和背景颜色，前景是`31~37`，背景是`41~47`，前景和背景都需要设置就用`;`隔开，比如`\33[31;43mhello\33[0m` 也可以十六进制 `\x1b[31;43mhello\x1b[0m`
> 
> ![image](https://user-images.githubusercontent.com/8625829/145021194-d72096fb-edfb-4179-8212-c69abdc49058.png)

那么字体和字号可以自己设置么？

**Comment by XXXXzzzz000** [comment]
您的邮件我已收到。                                                             宣泽
