### ISSUE TITLE
增加换行机制

### ISSUE THREAD

**Issue by GImDX** [Neutree/COMTool#84]
能否增加接收区除超时换行外的其他换行机制，Win等实时性并不好，对于数十毫间隔的包换行并不可靠，经常两帧显示在同一行或帧中切断换行，如：

1. 固定长度换行（ASCII和HEX）；
2. 检测到固定序列（帧头或帧尾），在帧头前插入换行或在帧尾后插入换行；

**Comment by Neutree** [comment]
也许可以用自定义协议插件？ 自定义python脚本去解析协议后用 print 打印你想打印的

**Comment by GImDX** [comment]
> 也许可以用自定义协议插件？ 自定义python脚本去解析协议后用 print 打印你想打印的

由于我的需求比较简单，传感器一帧的长度是固定的，只是频率比较高100Hz，导致buffer里面经常有两到三帧，不会python，研究了下您的代码，在dbg插件的基础上改了下，勉强能用😄
