### ISSUE TITLE
发收

### ISSUE THREAD

**Issue by xixiznaopq** [Neutree/COMTool#86]
![image](https://user-images.githubusercontent.com/99386251/210231298-58974300-b703-4857-92ad-e71f815edfde.png)
我打开发送文件，然后把所有的东西发完了之后，自己会出现这种情况。

**Comment by Neutree** [comment]
这看起来像是对方发过来的吧 不像是软件的问题诶

**Comment by xixiznaopq** [comment]
板子放在那里没有动，好奇怪哦

**Comment by Neutree** [comment]
板子的软件回复了什么不可见ascii码

**Comment by xixiznaopq** [comment]
没有读取出来？那这块代码我在那里操作呢

**Comment by Neutree** [comment]
你自己写的代码呀 。。。。 我咋知道嘞

**Comment by xixiznaopq** [comment]
问题是我没有写什么代码操作就是这样子的，所以我才问你写在那块

**Comment by Neutree** [comment]
没复现出来你的现象 不太清楚

**Comment by Neutree** [comment]
关闭问题  因为复现步骤描述不清晰，若仍然有问题欢迎重新打开交流
