### ISSUE TITLE
如何发送 Ctrl+C

### ISSUE THREAD

**Issue by trycatchx** [Neutree/COMTool#87]
Ctrl+C：送SIGINT信号，默认进程会结束

**Comment by Neutree** [comment]
发送十六进制数据 `03` 就好了，参考 [google 搜索结果](https://www.google.com.hk/search?q=ctrl+c+hex+vode&newwindow=1&sxsrf=ALiCzsbcxLAIixV3w5ZV9z1Xfl8PF_bdAg%3A1672717005722&source=hp&ei=zaKzY6ThKabNkPIPlImHuAU&iflsig=AJiK0e8AAAAAY7Ow3bta2OHogAUYKjXPWOTr0UVg2cX6&ved=0ahUKEwjk-7u3vKr8AhWmJkQIHZTEAVcQ4dUDCAo&uact=5&oq=ctrl+c+hex+vode&gs_lcp=Cgdnd3Mtd2l6EAM6BAgjECc6EQguEIAEELEDEIMBEMcBENEDOhEILhCDARDHARCxAxDRAxCABDoICAAQgAQQsQM6CwgAEIAEELEDEIMBOgUIABCABDoICAAQsQMQgwE6DgguEIAEELEDEMcBENEDOggILhCABBDUAjoICC4QgAQQsQM6CgguEIAEELEDEAo6CggAEIAEELEDEAo6BwgAEIAEEAo6DQgAEIAEELEDEIMBEAo6DQguEIAEEMcBEK8BEAo6CwguEIAEEMcBEK8BOg0ILhCvARDHARCABBAKOggIABCABBDLAToGCAAQFhAeOggIABAWEB4QDzoFCAAQhgM6BQghEKABOgUIIRCrAjoICCEQFhAeEB06CwghEBYQHhDxBBAdUABYpB5gxh9oAHAAeACAAfoBiAGnGZIBBDItMTSYAQCgAQE&sclient=gws-wiz)
