### ISSUE TITLE
TCP server没有启动？

### ISSUE THREAD

**Issue by SSSDNSY** [Neutree/COMTool#88]
![image](https://user-images.githubusercontent.com/15624361/211974032-cc22206a-9e36-4fd6-a532-20cbb04d8e42.png)
![image](https://user-images.githubusercontent.com/15624361/211974143-5b751c0d-53fb-40fc-8d33-55e3001782ac.png)
如图，使用nettyClient的Java代码链接本地端口8997，但是本地端口的服务貌似没有启动，多个8997server open也不会报冲突，
![image](https://user-images.githubusercontent.com/15624361/211974274-8001f59b-3315-4916-a66c-dab1090cced5.png)
shi'yon使用NetWork Assistant无问题。

**Comment by Neutree** [comment]
我试了试，好像是第二次打开的时候会无法打开，你重启软件第一次打开试试，像是个 bug

**Comment by YI--** [comment]
> 我试了试，好像是第二次打开的时候会无法打开，你重启软件第一次打开试试，像是个 bug

大佬，我这边也存在这个问题（第一次也是不行），试了Windows和Mac，TCP/IP下都无法正确建立 Server；
在终端中去搜对应的端口状态，发现是没有开启的。

**Comment by Neutree** [comment]
@YI--  可以说一下复现步骤和截图，我试了是可以的，并且用 netassistant 测了一下，如图：
![image](https://user-images.githubusercontent.com/8625829/232745362-9bfbf35a-d17a-4d49-83e0-c56cb318849f.png)

**Comment by YI--** [comment]
> 

默认端口是没有问题的（2345）` lsof -i tcp:2345  ` 端口也是通过的，目前的问题是只要修改了端口，如8080，软件显示启动了，但系统实际  ` lsof -i tcp:8080  `  的端口时是没有的（问题应该是修改端口的时候后续方法没有生效？）；
如图 
<img width="886" alt="image" src="https://user-images.githubusercontent.com/10511182/232750899-b50c6164-4ee3-45e3-805d-2929dde09a3b.png">

<img width="886" alt="iShot_2023-04-18_18 31 06" src="https://user-images.githubusercontent.com/10511182/232750963-0454cd46-e4b8-4f36-9e2f-399c96cac663.png">

还有一个问题，设置server端口是如果不是全选修改情况下会卡死，如：端口 2345，一个一个删除是到删除2的时候程序就直接卡死了，需求强制退出。

**Comment by Neutree** [comment]
修复了一下关闭和多次打开失败的问题：  https://github.com/Neutree/COMTool/commit/8a38e496335fc28d5dde4b130e1a96cf73569fdf

**Comment by YI--** [comment]
> @YI-- 试试我改过之后最新的源码运行试试，看问题是否仍然存在
> 
> 如果你有能力的话也可以用源码调试看看问题在哪儿 加 print 来调试就好了， 代码基本都在 [conn_tcp_udp.py](https://github.com/Neutree/COMTool/blob/master/COMTool/conn/conn_tcp_udp.py)

好的，感谢，我刚刚试了下发现我pyinstaller环境变量有点问题，我先搞下环境 😭

**Comment by Neutree** [comment]
是端口修改没有生效，只有默认的2345 端口有效，  #96  已经修复，感谢 @YI--
