### ISSUE TITLE
输出显示乱码，UTF-8、ASCII、GBK每一个我都试了，还是会乱码

### ISSUE THREAD

**Issue by ericsource** [Neutree/COMTool#90]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/22975499/218926511-3b72602a-a7b2-44ea-b258-81bc8e8bb6ca.png">

**Comment by Neutree** [comment]
参数错了把，波特率校验位啥的

**Comment by Neutree** [comment]
除了波特率错误也有可能没有共地， 仍然有问题再打开 issue 或者重开 issue
