### ISSUE TITLE
图标问题

### ISSUE THREAD

**Issue by zhaixiao214** [Neutree/COMTool#91]
![捕获1](https://user-images.githubusercontent.com/58213831/221114587-1c7d042c-fc35-447d-9505-91797a1268e1.PNG)
![捕获](https://user-images.githubusercontent.com/58213831/221114643-9075e76b-81e7-4b56-8601-01882bfb12be.PNG)
如图，有关清除图标的那行代码跑不起来，请问清除图标是在哪定义的啊

**Comment by Neutree** [comment]
应该和 #59 是同一个问题，参考一下
