### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by KingingWang** [Neutree/COMTool#92]
```shell
(comtools) root@jupyter:~/COMTool# comtool
2023-03-01 07:55:46 - [INFO] -  Config path: /root/.config/comtool/config.json
2023-03-01 07:55:46 - [INFO] -  Log path: /root/.config/comtool/run.log
2023-03-01 07:55:46 - [INFO] -  loading config from /root/.config/comtool/config.json
2023-03-01 07:55:46 - [INFO] -  loading config complete
-- set locale to en
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted
```

**Comment by Neutree** [comment]
应该是差什么依赖 可以 先执行`export QT_DEBUG_PLUGINS=1` 看看调试信息， 也许  https://neucrack.com/p/407 有参考意义

**Comment by KingingWang** [comment]
> 

sudo apt install python3-pyqt5
我以为只有树莓派要这个,原来所有的都要

**Comment by Neutree** [comment]
不是啊，如果你下载的二进制包理论上就不需要的；
如果你是源码安装比如 pip install comtool 它会自己下载

**Comment by KingingWang** [comment]
就源码编译安装,没有自动安装,`pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple`也执行了

**Comment by Neutree** [comment]
你是什么系统，我用我最近新装的ubuntu22.04，直接`pip install comtool -i https://pypi.douban.com/simple` 

可以看到自动装了 pyqt5:
![image](https://user-images.githubusercontent.com/8625829/222091917-c789765c-80e9-43ad-a534-8a10034e678d.png)

直接 `comtool` 就能启动

![image](https://user-images.githubusercontent.com/8625829/222092266-dcea7261-3c3e-4ecd-bc44-bd9fe6658612.png)

**Comment by KingingWang** [comment]
我没有`pip install comtool -i https://pypi.douban.com/simple`我是想源码直接编译的,就直接`pip install -r requirements.txt`

**Comment by Neutree** [comment]
那没啥区别

**Comment by Neutree** [comment]
> 应该是差什么依赖 可以 先执行`export QT_DEBUG_PLUGINS=1` 看看调试信息， 也许 https://neucrack.com/p/407 有参考意义

按照这个看看却啥依赖吧 调一调

**Comment by Neutree** [comment]
噢你已经解决了 那就行

**Comment by BunnySakura** [comment]
如果pip安装成功但是执行`comtool`显示找不到命令，执行：
```shell
python -m COMTool.Main
```

为了方便使用，可以写一个别名，即可执行`comtool`。这里以Zsh举例，Bash差不多：
```shell
nano ·/.zshrc # 编辑zsh配置
```

在最后一行添加：
```shell
alias comtool='python -m COMTool.Main' # 指定别名comtool
```
