### ISSUE TITLE
linux端串口终端不能拷贝

### ISSUE THREAD

**Issue by haifengjia** [Neutree/COMTool#94]
- OS: Ubuntu 22.04
- Version: 3.1.3
- Terminal: /dev/ttyACMx

请问在这种情况下该如何拷贝？尝试过`ctrl c`, `ctrl shift c`和鼠标中键。想问一下是没有这个功能，还是我快捷键没有按对？如果哪位知晓的兄弟能回答一下的话非常感谢！

![image](https://user-images.githubusercontent.com/52434357/227761692-f394a8f5-2890-4f9f-a405-c7bf8460f802.png)

**Comment by Neutree** [comment]
鼠标选中，然后鼠标右键 就自动复制好了，要粘贴，再点一下右键就好了
