### ISSUE TITLE
windows下该如何使用pip安装comtool？

### ISSUE THREAD

**Issue by Tilie** [Neutree/COMTool#95]
我有需求使用crc功能。所以需要在Windows下使用pip安装的版本

pip install 之后。直接在powershell内执行comtool后没有弹出任何窗口。

有什么教程可以跟随吗

**Comment by Neutree** [comment]
直接执行 comtool 没有找到命令的话是没有把python的可执行程序路径加入系统环境变量，可能是你安装python的时候没勾上这个选项。

在 windows 下，pip 安装的命令都在`python安装路径/Scripts`目录下， 你可以手动将`python安装路径/Scripts`目录添加到系统环境变量`Path`里面，然后重新打开终端应该就能执行 comtool 了

**Comment by Tilie** [comment]
在powershell里执行时并不是弹出那个“找不到对应程序的”的提示。

我找到了你说的那个exe，无论是双击运行还是管理员权限。都没能打开。

请问是有什么依赖吗？

**Comment by Neutree** [comment]
理论上依赖会自动安装才对

那你直接用源码运行试试吧，克隆源码到本机，然后执行 `python3 COMTool/Main.py`

**Comment by Tilie** [comment]
查出来了 是pillow 这个库没安装上。
感谢你的帮助

**Comment by Neutree** [comment]
可能是因为有个3dTOF的插件导致的，mark一下，后面把这个插件删除掉
